name: Deploy infra and app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: study-app-001
  RESOURCE_GROUP: study-rg
  NODE_VERSION: '20.x'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure resources by Bicep
        run: |
          az deployment sub create \
            --location japaneast \
            --template-file main.bicep \
            --parameters \
              rgName=study-rg \
              rgLocation=japaneast \
              mysqlLocation=koreacentral \
              appLocation=malaysiawest \
              serverName=study-mysql-youth001 \
              dbName=study_db \
              adminUser=adminuser \
              adminPassword='${{ secrets.DB_ADMIN_PASSWORD }}' \
              storageName=studystorageyouth001 \
              containerName=images \
              keyVaultName=study-kv-youth001 \
              appName=study-app-001 \
              planName=study-app-plan \
              operatorObjectId=c859a37d-4699-4a84-b9af-c934b8c4954f \
              kvMode=recover

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Create deployment package
        run: |
          zip -r app.zip . \
            -x ".git/*" \
            -x ".github/*"

      - name: Deploy app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip